{% set name = "mne-icalabel" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cf3c2031a01de9f95ff5af6743137afaab23fd9a48b95f22a4264eb50c23ddbd

build:
  number: 0

outputs:
  - name: mne-icalabel-base
    build:
      noarch: python
      script: python -m pip install . -vv
      entry_points:
        - mne_icalabel-sys_info = mne_icalabel.commands.sys_info:run
        - mne_gui_ic_annotation = mne_icalabel.commands.mne_gui_ic_annotation:main

    requirements:
      host:
        - pip
        - python >=3.9
        - setuptools >=64.0.0
      run:
        - joblib  # ICA
        - matplotlib-base  # GUI
        - mne-base >=1.2
        - mne-qt-browser  # GUI
        - numpy >=1.21
        - packaging
        - pooch
        - psutil
        - python >=3.9
        - python-picard  # ICA
        - qtpy  # GUI
        - scikit-learn  # ICA
        - scipy >=1.2.0

    test:
      imports:
        - mne_icalabel
      requires:
        - pip
      commands:
        - pip check
        - mne_icalabel-sys_info

  - name: mne-icalabel
    requirements:
      run:
        - {{ pin_subpackage('mne-icalabel-base', max_pin="x.x.x.x") }}
        - pytorch

    test:
      imports:
        - mne_icalabel
      requires:
        - pip
      commands:
        - mne_icalabel-sys_info

about:
  home: https://mne.tools/mne-icalabel/stable/
  summary: MNE-ICALabel is a Python package for labeling independent components that stem from an Independent Component Analysis (ICA).
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/mne-tools/mne-icalabel

extra:
  recipe-maintainers:
    - hoechenberger
    - larsoner
    - adam2392
    - mscheltienne
