{% set name = "mne-icalabel" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 6906e5d75a19d6a3023dc1b5146b4fce8c3767b1c02769c22c53600a1039067c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - mne_icalabel-sys_info = mne_icalabel.commands.sys_info:run
    - mne_gui_ic_annotation = mne_icalabel.commands.mne_gui_ic_annotation:main

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools >=64.0.0
  run:
    - joblib  # ICA
    - matplotlib-base  # GUI
    - mne-base >=1.2
    - mne-qt-browser >=0.6.0 # GUI
    - numpy >=1.21
    - onnxruntime
    - packaging
    - pooch
    - psutil
    - python >=3.9
    - python-picard  # ICA
    - qtpy  # GUI
    - scikit-learn  # ICA
    - scipy >=1.4.0

test:
  imports:
    - mne_icalabel
  requires:
    - pip
  commands:
    - pip check
    - mne_icalabel-sys_info

about:
  home: https://mne.tools/mne-icalabel/stable/
  summary: MNE-ICALabel is a Python package for labeling independent components that stem from an Independent Component Analysis (ICA).
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/mne-tools/mne-icalabel

extra:
  recipe-maintainers:
    - hoechenberger
    - larsoner
    - adam2392
    - mscheltienne
